from technical_indicators_lib.indicators import (
    ADI, ATR, CMF, CHO, CHV, DPO, EMV, EMA, FI, MI, MED, MOM,
    MFI, MACD, NVI, OBV, PVT, PC, PO, ROC, ROCV, RSI, SMA, VLT, StochasticKAndD,
    Trix, TR, TYP, VHF, VO, WCL
)
adi = ADI()
atr = ATR()
cmf = CMF()
cho = CHO()
chv = CHV()
dpo = DPO()
emv = EMV()
ema = EMA()
fi = FI()
mi = MI()
mem = MED()
mom = MOM()
mfi = MFI()
macd = MACD()
nvi = NVI()
obv = OBV()
pvt = PVT()
pc = PC()
po = PO()
roc = ROC()
rocv = ROCV()
rsi = RSI()
sma = SMA()
vlt = VLT()
stochastic_k_and_d = StochasticKAndD()
trix = Trix()
tr = TR()
typ = TYP()
vhf = VHF()
vo = VO()
wcl = WCL()
